#!/bin/bash
riverctl rule-add ssd

riverctl rule-add -title "Open File" float
riverctl rule-add -title "Open Folder" float
riverctl rule-add -app-id nm-openconnect-auth-dialog float
riverctl rule-add -app-id org.pulseaudio.pavucontrol float
riverctl rule-add -app-id blueman-manager float
riverctl rule-add -app-id org.gnupg.pinentry-qt float

function spawn_once {
  pgrep -f "${1}" >/dev/null || riverctl spawn "${*} >/tmp/river/${1}.${XDG_VTNR}.${USER}.log 2>&1"
}

spawn_once 'firefox'
riverctl rule-add -app-id  org.mozilla.firefox tags $((1 << 9))
riverctl map normal Mod1 0 spawn "riverctl set-focused-tags $((1 << 9))"
riverctl map normal Mod1+Shift 0 spawn "riverctl toggle-focused-tags $((1 << 9))"

spawn_once 'alacritty'
riverctl rule-add -app-id Alacritty tags $((1 << 1))
riverctl map normal Mod1 1 spawn "riverctl toggle-focused-tags $((1 << 1))"
riverctl map normal Mod1+Shift 1 spawn "riverctl set-focused-tags $((1 << 1))"

spawn_once qutebrowser
riverctl rule-add -app-id org.qutebrowser.qutebrowser tags $((1 << 2))
riverctl map normal Mod1 2 spawn "riverctl toggle-focused-tags $((1 << 2))"
riverctl map normal Mod1+Shift 2 spawn "riverctl set-focused-tags $((1 << 2))"

spawn_once "flatpak run com.slack.Slack"
riverctl rule-add -app-id com.slack.Slack tags $((1 << 3))
riverctl map normal Mod1 3 spawn "riverctl toggle-focused-tags $((1 << 3))"
riverctl map normal Mod1+Shift 3 spawn "riverctl set-focused-tags $((1 << 3))"

riverctl spawn 'google-chrome-stable --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan' #meet
riverctl rule-add -app-id "*kjgfgldnnfoeklkmfkjfagphfepbbdan*" tags $((1 << 4))
riverctl map normal Mod1 4 spawn "riverctl toggle-focused-tags $((1 << 4))"
riverctl map normal Mod1+Shift 4 spawn "riverctl set-focused-tags $((1 << 4))"

riverctl rule-add -app-id "Cursor" tags $((1 << 5))
riverctl map normal Mod1 5 spawn "riverctl toggle-focused-tags $((1 << 5))"
riverctl map normal Mod1+Shift 5 spawn "riverctl set-focused-tags $((1 << 5))"

#Floats
spawn_once 'google-chrome-stable --app-id=caidcmannjgahlnbpmidmiecjcoiiigg' #gemini
riverctl rule-add -title "*Gemini*" float
riverctl rule-add -title "*Gemini*" tags $((1 << 21))
riverctl map normal Mod1 Return spawn "riverctl toggle-focused-tags $((1 << 21))"

spawn_once 'google-chrome-stable --app-id=kjbdgfilnfhdoflbpgamdcdgpehopbep' #rh-calendar
riverctl rule-add -title "*Calendar*" float
riverctl rule-add -title "*Calendar*" tags $((1 << 22))
riverctl map normal Mod1 9 spawn "riverctl toggle-focused-tags $((1 << 22))"

spawn_once "flatpak run com.spotify.Client"
riverctl rule-add -app-id Spotify float
riverctl rule-add -app-id Spotify tags $((1 << 23))
riverctl map normal Mod1 Backspace spawn "riverctl toggle-focused-tags $((1 << 23))"

spawn_once spawn "flatpak run org.signal.Signal"
riverctl rule-add -app-id Signal float
riverctl rule-add -app-id Signal dimensions 1024 768
riverctl rule-add -app-id Signal position 60 60
riverctl rule-add -app-id Signal tags $((1 << 20))
riverctl map normal Mod1 Backslash spawn "riverctl toggle-focused-tags $((1 << 20))"

# riverctl rule-add -app-id "google-chrome" -title "*RedHat*" tags $((1 << 8))
# riverctl map normal Mod1 5 spawn 'riverctl toggle-focused-tags $((1 << 8))'
# riverctl map normal Mod1+Shift 5 spawn 'riverctl set-focused-tags $((1 << 8))'

# riverctl rule-add -app-id google-chrome tags $((1 << 7))
# riverctl map normal Mod1 0 spawn 'riverctl set-focused-tags $((1 << 7))'
# riverctl map normal Mod1+Shift 0 spawn 'riverctl toggle-focused-tags $((1 << 7))'
#
#org.wireshark.Wireshark: Capturing from Standard input [metallb-system/metallb-operator-controller-manager-64d685bff9-g6snd/manager]
#google-chrome: New Tab - Google Chrome
