#!/bin/bash
riverctl rule-add ssd

riverctl rule-add -title "Open File" float
riverctl rule-add -title "Open Folder" float
riverctl rule-add -app-id nm-openconnect-auth-dialog float
riverctl rule-add -app-id org.pulseaudio.pavucontrol float
riverctl rule-add -app-id blueman-manager float

#riverctl spawn 'chromium-browser'
riverctl spawn 'flatpak run app.zen_browser.zen'
#riverctl rule-add -app-id chromium-browser tags $((1 << 7))
riverctl rule-add -app-id zen tags $((1 << 7))
riverctl map normal Mod1 0 spawn 'riverctl set-focused-tags $((1 << 7))'
riverctl map normal Mod1+Shift 0 spawn 'riverctl toggle-focused-tags $((1 << 7))'

#riverctl spawn 'ghostty'
#riverctl rule-add -app-id com.mitchellh.ghostty tags $((1<<0))
riverctl spawn 'alacritty -T main'
riverctl rule-add -app-id Alacritty -title "main" tags $((1 << 0))
riverctl map normal Mod1 1 spawn "riverctl toggle-focused-tags 1"
riverctl map normal Mod1+Shift 1 spawn "riverctl set-focused-tags 1"

riverctl spawn qutebrowser
riverctl rule-add -app-id org.qutebrowser.qutebrowser tags $((1 << 1))
riverctl map normal Mod1 2 spawn "riverctl toggle-focused-tags 2"
riverctl map normal Mod1+Shift 2 spawn "riverctl set-focused-tags 2"

riverctl spawn "flatpak run com.slack.Slack"
riverctl rule-add -app-id com.slack.Slack tags $((1 << 2))
riverctl map normal Mod1 3 spawn "riverctl toggle-focused-tags 4"

#google-chrome: Google Meet
#chrome-kjgfgldnnfoeklkmfkjfagphfepbbdan-Default: Google Meet - Meet - pzh-rigd-udw

riverctl rule-add -title "*Google Meet*" tags $((1 << 4))
riverctl spawn "Google Meet"
riverctl map normal Mod1 4 spawn 'riverctl toggle-focused-tags $((1<<4))'

# riverctl rule-add -app-id Alacritty -title "aichat" float
# riverctl rule-add -app-id Alacritty -title "aichat" dimensions 1024 1100
# riverctl rule-add -app-id Alacritty -title "aichat" position 640 60
#riverctl spawn 'alacritty -T aichat'
riverctl spawn 'google-chrome-stable --app-id=caidcmannjgahlnbpmidmiecjcoiiigg' #gemini
#riverctl rule-add -app-id Alacritty -title "aichat" tags $((1 << 3))
riverctl rule-add -title "*Gemini*" tags $((1 << 3))
riverctl map normal Mod1 Return spawn 'riverctl toggle-focused-tags $((1 << 3))'

riverctl rule-add -title "*Calendar*" float
riverctl rule-add -title "*Calendar*" tags $((1 << 5))
riverctl map normal Mod1 9 spawn 'riverctl toggle-focused-tags $((1 << 5))'

riverctl rule-add -app-id Spotify float
riverctl rule-add -app-id Spotify dimensions 1024 768
riverctl rule-add -app-id Spotify position 1536 5
riverctl spawn "flatpak run com.spotify.Client"
riverctl rule-add -app-id Spotify tags $((1 << 6))
riverctl map normal Mod1 Backspace spawn 'riverctl toggle-focused-tags $((1 << 6))'

riverctl rule-add -app-id Signal float
riverctl rule-add -app-id Signal dimensions 1024 768
riverctl rule-add -app-id Signal position 60 60
riverctl spawn "flatpak run org.signal.Signal"
riverctl rule-add -app-id Signal tags $((1 << 20))
riverctl map normal Mod1 Backslash spawn 'riverctl toggle-focused-tags $((1 << 20))'

# riverctl rule-add -app-id "google-chrome" -title "*RedHat*" tags $((1 << 8))
# riverctl map normal Mod1 5 spawn 'riverctl toggle-focused-tags $((1 << 8))'
# riverctl map normal Mod1+Shift 5 spawn 'riverctl set-focused-tags $((1 << 8))'

# riverctl rule-add -app-id google-chrome tags $((1 << 7))
# riverctl map normal Mod1 0 spawn 'riverctl set-focused-tags $((1 << 7))'
# riverctl map normal Mod1+Shift 0 spawn 'riverctl toggle-focused-tags $((1 << 7))'
#
#org.wireshark.Wireshark: Capturing from Standard input [metallb-system/metallb-operator-controller-manager-64d685bff9-g6snd/manager]
#google-chrome: New Tab - Google Chrome
