#!/bin/bash

riverctl map normal Mod1 O spawn fuzzel
mod="Mod1"

gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"

"$HOME"/.config/river/init.d/startup
"$HOME"/.config/river/init.d/apps

riverctl map normal Mod1 j focus-view next
riverctl map normal Mod1 k focus-view previous
riverctl map normal Mod1 f toggle-fullscreen
riverctl map normal Mod1 Space zoom
riverctl map normal Mod1+Shift J swap down
riverctl map normal Mod1+Shift K swap up

riverctl map normal Mod1+Shift F toggle-float
riverctl map normal Mod1+Shift Q close

riverctl map normal Mod1 Left focus-output left
riverctl map normal Mod1 Right focus-output right
riverctl map normal Mod1+Shift Right send-to-output right
riverctl map normal Mod1+Shift Down send-to-output down
riverctl map normal Mod1+Shift Left send-to-output left
riverctl map normal Mod1+Shift Up send-to-output up

riverctl map normal Mod1 Tab focus-previous-tags

#spawn
riverctl map normal $mod m spawn 'swaylock -c 000000 -F -k -l -e -i ~/.config/wallpapers/redhat.png'
riverctl map normal $mod p spawn tessen
riverctl map normal $mod+Shift V spawn "cliphist list | fuzzel -d | cliphist decode | wl-copy"

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

riverctl default-attach-mode top
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-output-change
riverctl focus-follows-cursor disabled

#riverctl map normal Mod1+Shift H send-layout-cmd rivertile "main-count +1"
#riverctl map normal Mod1+Shift L send-layout-cmd rivertile "main-count -1"
# riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"
# riverctl map normal $mod+Alt J move down 100

for mode in normal locked; do
  riverctl map $mode None XF86AudioRaiseVolume spawn 'volctl.sh up'
  riverctl map $mode None XF86AudioLowerVolume spawn 'volctl.sh down'
  riverctl map $mode None XF86AudioMute spawn 'volctl.sh mute'
  riverctl map $mode None XF86AudioMicMute spawn 'volctl.sh micmute'
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'
  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
  riverctl map $mode None Print spawn 'grim -g "$(slurp)" \- | wl-copy'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x008800
riverctl border-color-unfocused 0x586e75
riverctl border-width 5

riverctl keyboard-layout -options 'ctrl:nocaps,grp:win_space_toggle' 'us,gr'

riverctl default-layout rivertile
rivertile -view-padding 1 -outer-padding 0 -main-location left & #--main-ratio 0.7 &
